### PR TITLE
Unit tests for ImageScraper class

### PR DESCRIPTION
**Pull request by nathanIL**
Unit tests for the ImageScraper class.
Added another requirements file (requirements-dev.txt) for development dependencies (could be used in Travis-CI for instance).

### CODE REVIEW

**Comment by nathanIL** [comment]
P.S: The commit is ef43178.
The rest to make unittest branch updated.

Btw, why do we need a unittest branch?

**Comment by NaveenKarippai** [comment]
I didn't complete writing the unittest. I thought it would be a better idea to start in a new branch and later merge it to master?

**Comment by nathanIL** [comment]
Thanks for the feedback! much appreciated!

I will check the _unittest_ branch now for the new updates.
As for merging to _master_ branch, this is also an option. In my case, tests are always available both the the _master_ and bleeding edge one (e.g: _develop_ ,etc...)

**Comment by NaveenKarippai** [comment]
You have a point! I merged unittest branch to master.
Do you think it would be a good idea to make contributors.txt file and include your name + mail id?

**Comment by nathanIL** [comment]
Yes, I think it would be a good idea to merge these to _master_ branch.
As for the _CONTRIBUTORS_, some projects here on _Github_ does have this file, so could be an option.

**Comment by NaveenKarippai** [comment]
I have put CONTRIBUTORS file on master. It would be nice if you could add your name. :)

**Comment by nathanIL** [comment]
@NaveenKarippai 
I will, thanks!

**Pull request merged**
