### PR TITLE
Add travis-ci to project

### PR DESCRIPTION
**Pull request by nathanIL**
Add travis-ci with nosetest to run our tests on each merged commit.
See the project's description for the tests / build status.
Currently it runs well only on python 2.7+, we can easily add support for python 3 as well.

### CODE REVIEW

**Comment by NaveenKarippai** [comment]
Cool! I'm a noob to travis-ci api, Good that you showed up.

**Comment by NaveenKarippai** [comment]
@nathanIL 
A noob question : Do I need to create a travis-ci with original remote repo? 
The root of this question is I doubt if the original remote repo would update if you created it with linking your forked remote repo.

**Comment by nathanIL** [comment]
@NaveenKarippai 

Not a noob question at all, I'm also not so experienced with Travis. but its a very easy tool to configure and then you get a free CI.

Yes, configure a travis and set the project to use it. its pretty easy, let me know if you need help.

**Comment by NaveenKarippai** [comment]
Sure, Thanks. I will play around with Travis CI.
Could you please double check if there is a need for _requirements-dev.txt_ and _requirements.txt_ files seperately? Why can't it be merged?

**Comment by nathanIL** [comment]
@NaveenKarippai 

The reason for the double _requirements_ file is because one is used only for Dev, for instance, in Travis where its required to have the [HTTPretty](http://falcao.it/HTTPretty/) class that is only used for mocking during the tests phase **only**.
Basically what else we can do is use a common one, and another one that includes only the modules that are required during CI / tests, see [this](http://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments) for instance.

what do you think?

**Comment by NaveenKarippai** [comment]
Yes, that makes sense.

**Pull request merged**
